# Tor Daemon Service Configuration
name=tor
exec=/dev/tor
args=--defaults-torrc /etc/services/torrc --DataDirectory /tor/data
description=Tor Anonymity Network - Hidden Service
type=daemon
auto_start=true
restart_on_fail=true
high_priority=true
