"#ifndef __TCCDEFS__\n"
"#define __TCCDEFS__\n"
"#define __CHAR_BIT__ 8\n"
"#define __SIZEOF_SHORT__ 2\n"
"#define __SIZEOF_INT__ 4\n"
"#define __SIZEOF_LONG__ 4\n"
"#define __SIZEOF_LONG_LONG__ 8\n"
"#define __SIZEOF_FLOAT__ 4\n"
"#define __SIZEOF_DOUBLE__ 8\n"
"#define __SIZEOF_LONG_DOUBLE__ 12\n"
"#define __SIZEOF_SIZE_T__ 4\n"
"#define __SIZEOF_PTRDIFF_T__ 4\n"
"#define __builtin_expect(x,y) (x)\n"
"#define __builtin_unreachable() do{}while(0)\n"
"#define __builtin_trap() do{}while(0)\n"
"#define __builtin_constant_p(x) 0\n"
"#define __builtin_types_compatible_p(t1,t2) 0\n"
"#define __builtin_choose_expr(c,e1,e2) (e2)\n"
"#define __builtin_clz(x) 0\n"
"#define __builtin_ctz(x) 0\n"
"#define __builtin_popcount(x) 0\n"
"#define __builtin_bswap32(x) (x)\n"
"#define __builtin_bswap64(x) (x)\n"
"#define __builtin_frame_address(n) ((void*)0)\n"
"#define __builtin_return_address(n) ((void*)0)\n"
"#endif\n"
